### ISSUE TITLE
How to get all intent filters of an APK, or parse the manifest?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [caoqianli/apk-parser#19]
I'm new to this library.
Is there any manual about how to use it in order to parse the manifest file, to see which intent filters the APK declares?

**Comment by jaredrummler** [comment]
Just wanted to contribute a little to this conversation.

If you use this on Android and need support for devices below KitKat (API 19) you need to remove some Java 7 language features. Specifically:

* try-with-resources statements
* calls to `Objects.equals(Object a, Object b)`

_____

Instead of using `sun.security.pkcs.PKCS7` you can get the certificate with `javax.security.cert.X509Certificate#getInstance(byte[] certData);`

**Comment by AndroidDeveloperLB** [comment]
@jaredrummler Oops. Sorry for forgetting about JDK7.
I don't remember what I did with the PKCS7 ...  Maybe I used what you wrote.

**Comment by AndroidDeveloperLB** [comment]
Hey, I'm back to trying this library on Android, and this time I wish to publish a port of it for Android.
How come "getIntentFilters" isn't available? 


@jaredrummler The class you've offered doesn't seem to have a function that's similar to "getCertificates" , as used on CertificateParser::parse :

        PKCS7 pkcs7 = new PKCS7(Utils.toByteArray(in));
        X509Certificate[] certificates = pkcs7.getCertificates();

Thank you for the other stuff. Lint also helps with that.

**Comment by AndroidDeveloperLB** [comment]
@CaoQianLi Can you please show how to use the new version of the repo, with the changes of the intent-filter parsing? For some reason, I don't see the functions of the intent-filter parsing...

**Comment by CaoQianLi** [comment]
CertificateParser is used for get certificate info.
Newer version do not provide method to get intent-filters,  you may refer to older code.

**Comment by AndroidDeveloperLB** [comment]
@CaoQianLi 
1. Why was the intent-filter parsing removed? How do I get it back?
2. Is it now using less memory than before? I remember it used a lot sometimes, which would trigger Out-of-memory-exception ...
3. Could you make the built-in files reading a bit more flexible, as I've written, so that I could tell it from outside how to get an InputStream out of a file name/path?

**Comment by jaredrummler** [comment]
Working version for Android: https://github.com/jaredrummler/apk-parser

**Comment by AndroidDeveloperLB** [comment]
@jaredrummler You've published before I did. :+1: )

**Comment by AndroidDeveloperLB** [comment]
@caoqianli  Can you please suggest what I could do further, to make it work faster, and with less memory usage, considering all I need is to get the intent-filters of the APK file?
