### ISSUE TITLE
Questions about the license

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [caoqianli/apk-parser#33]
Sorry for this, but I'm not a lawyer and English isn't my main language : 

1. Is it ok to port this repo to a project that works on Android, and publish it on Github?
2. Is it ok to use the library on a real app?
3. Do I have to make the app open sourced too? Make the part that uses this repo open sourced?
4. What exactly do I have to do?

**Comment by DongWenDao** [comment]
This lib is distributed under bsd 2 clause, and yes, you can use it for open source or commercial software. You should ship the license with your software source code(if distribute source code), or reproduce the license content in your documentation or something else. This is the only thing need to do.

**Comment by AndroidDeveloperLB** [comment]
What do you mean by "ship the license with software source code" ? 
If I use the repo using gradle, I can't even look at the license anymore.
Currently, I put the licenses information on the "about" window of the app. Is this ok ?

**Comment by CaoQianLi** [comment]
Yes, It's OK

**Comment by AndroidDeveloperLB** [comment]
@CaoQianLi It seems someone else has published a library for Android before I did:
https://github.com/jaredrummler/apk-parser

I wonder how well it works.
