### ISSUE TITLE
apk-parser on Google App Engine ?

### ISSUE THREAD

**Issue by guffyWave** [caoqianli/apk-parser#34]
Hey caoqianli , I am using Google App Engine Java at server end with Spring MVC too . You might be aware that GAE doesnot support java.io.FileOutputStream. When uploading a file(here apk file) Spring give a Multipart object which is org.springframework.web.multipart.MultipartFile class .Its very unfortunate that you ApkParser only takes File or String .Can you please make another constructer taking byte array of file .Thanks.

**Comment by caoqianli** [comment]
Add ByteArrayApkParser in version 2.1.0

**Comment by guffyWave** [comment]
Thanks pal for instant reply .
