### ISSUE TITLE
using getResourceEntry()

### ISSUE THREAD

**Issue by WisdomSky** [caoqianli/apk-parser#35]
I'm trying to get all the resources of an app..

https://github.com/caoqianli/apk-parser/blob/master/src/main/java/net/dongliu/apk/parser/struct/resource/Type.java#L30

the getResourceEntry method requires an $id argument...
I'm wondering what ID is this... is this the resource id or package id?
and how are we able to get the Resource ID list?

Can I recommend?
is it possible for you to add a getAllResourceEntries() method that we can use to fetch all resources under that specific type?

**Comment by caoqianli** [comment]
The id of Type.getResourceEntry argument is the resource entry index, which is the last two bytes of resource id:
```
resourceId(4 byte) = packageId(1byte) + typeId(1byte) + entryIndex(1byte)
```
All entries of a type can be get by:
```java
        long[] offsets = type.getOffsets();
        for (int i = 0; i < offsets.length; i++) {
            ResourceEntry resourceEntry = type.getResourceEntry(i);
            if (resourceEntry != null) {
                // ...
            }
        }
```

**Comment by WisdomSky** [comment]
Thanks!

I really have no proper understanding yet with the arsc file structure that's why I can't do byte by byte operation.

By the way, I found another package same as yours but this one is pretty much concise and it has what I need... the getting of all resources of a package.

https://github.com/WisdomSky/soot-infoflow-android/tree/develop/src/soot/jimple/infoflow/android/resources
