### ISSUE TITLE
Null icon name in parsed manifest

### ISSUE THREAD

**Issue by mampcs** [caoqianli/apk-parser#43]
I found that the icon name is null for the following attached apk.
Version 2.1.1 works fine for this apk.
Version 2.1.2 results in the following exception: java.lang.NumberFormatException: For input string: "0x20000"
Version 2.1.3 onwards results in an empty icon name.

[missing.icon.name.zip](https://github.com/caoqianli/apk-parser/files/417289/missing.icon.name.zip)

**Comment by caoqianli** [comment]
A bug introduced recently.
Fixed in: https://github.com/caoqianli/apk-parser/commit/dfe77700c3f22973449f047f0d8d61c113de752b

**Comment by mampcs** [comment]
Verified the fix. Thanks again for the quick response.
